# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
