# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uesr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
