# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_article_uesr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uesr_id',
            new_name='uesr',
        ),
    ]
