# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200318_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upanddown',
            name='article',
        ),
        migrations.RemoveField(
            model_name='upanddown',
            name='user',
        ),
        migrations.DeleteModel(
            name='UpAndDown',
        ),
    ]
